Web.App.Frontend/Models/BookModel.cs
namespace Web.App.Frontend.Models
{
    public class BookModel
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public decimal Price { get; set; }
        public string? ISBN {  get; set; }
        public string? Remarks { get; set; }
    }
}

Web.App.Frontend/Models/Person.cs
namespace Web.App.Frontend.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Age { get; set; }
    }
}

Web.App.Frontend/Controllers/BookController.cs
namespace Web.App.Frontend.Controllers
{
    public class BookController : Controller
    {
        public ViewResult SingleBook()
        {
            var bookModel = new BookModel
            {
                Id = 1,
                Title = "Professional C# 7 and .NET Core 2.0",
                Price = 47.99M,
                ISBN = "9781119449270",
                Remarks = "The best-selling C# book"
            };

            HttpContext.Session.Set("book", bookModel);

            HttpContext.Session.Set("isvalid", true);
            return View();
        }

        public ViewResult DisplayBook()
        {
            var book = HttpContext.Session.Get<BookModel>("book");
            return View(book);
        }

        public ViewResult Detail(int? id,  string title)
        {
            var book = new BookModel
            {
                Id = id ?? 0,
                Title = title
            };

            return View(book);
        }

        public ActionResult Go()
        {
            return RedirectToAction("Detail", new { id = 100, title = "PHP" });
        }
    }
}

Web.App.Frontend/Controllers/GalleryController.cs
namespace Web.App.Frontend.Controllers
{
    public class GalleryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Create(string name, string email, int age, bool? btn)
        {
            ViewBag.Name = name;
            ViewBag.Email = email;
            ViewBag.Age = age;
            ViewBag.isSubmitted = btn;

            return View();
        }
    }
}

Web.App.Frontend/Controllers/HomeController.cs
namespace Web.App.Frontend.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            // passing data from controller to view.


            ViewBag.Username = "Walidad";
            ViewBag.Age = 22;
            ViewBag.HasJob = true;

            ViewBag.ComplexData = new { Id = 1, Name = "Aijaz" };


            //TempData["Username"] = "Walidad";
            //TempData["Age"] = 22;
            //TempData["HasJob"] = true;

            //TempData["ComplexData"] =
            //    JsonSerializer.Serialize<dynamic>(new { Id = 1, Name = "Aijaz" });

             return View();

            //return RedirectToAction("About");
        }

        public ViewResult About()
        {
            return View();
        }

        public ViewResult Contact() 
        { 
            return View("ContactUs");
        }


        public JsonResult GetUser()
        {
            var user = new
            {
                Id = 1,
                Name = "Walidad",
                Age = 30,
                Books = new[] { "Java", "Php", "C#", "Python" }
            };


            return Json(user);

        }


        public ViewResult Book()
        {
            ViewBag.Title = "Book";

            var book = new BookModel
            {
                Id = 1,
                Title = "Java",
                ISBN = "RT658UYU",
                Price = 52.5m
            };

            return View(book);
        }


        public ViewResult BookList()
        {
            ViewBag.Title = "Book List";

            var bookList = new List<BookModel>
            {
                 new() { Id = 1, Title = "Java", ISBN = "RT658UYU", Price = 52.5m },
                 new() { Id = 2, Title = "C#", ISBN = "RT6785U", Price = 50.5m },
                 new() { Id = 3, Title = "Php", ISBN = "RT658UYU", Price = 58.5m },
                 new() { Id = 4, Title = "Python", ISBN = "RT658UYU", Price = 11.5m },
                 new() { Id = 5, Title = "React", ISBN = "RT658UYU", Price = 500.5m },
                 new() { Id = 6, Title = "Oracle", ISBN = "RT658UYU", Price = 215.5m }
            }
            .OrderBy(b => b.Title)
            .ToList();

            return View(bookList);
        }

        public ViewResult SaveBook()
        {
            ViewBag.Title = "Save Book";

            return View();
        }


        [HttpPost]
        public ViewResult SaveBook(BookModel book)
        {
            ViewBag.Title = "Book Saved!";
            return View(book);
        }


        public ViewResult PersonDetails(int id, string name, int age)
        {
            var person = new Person
            {
                Id = id,
                Name = name,
                Age = age
            };

            return View(person);
        }

    }
}

Web.App.Frontend/Controllers/ProductController.cs
namespace Web.App.Frontend.Controllers
{

    // Attribute routing
    //[Route("shop")]
    public class ProductController : Controller
    {

        //[Route("plist")]
        //public ViewResult Products()
        //{
        //    return View();
        //}

        public ViewResult Products()
        {
            HttpContext.Session.SetString("Name", "Walidad Brohi");
            HttpContext.Session.SetInt32("Age", 22);

            return View();
        }


    }
}

Web.App.Frontend/Views/Book/Detail.cshtml
@model BookModel

<pre>
    @Model.Id
    @Model.Title
</pre>

Web.App.Frontend/Views/Book/DisplayBook.cshtml
@model BookModel


@if (Model == null)
{
    <p>Book not found</p>
    return;
}

<pre>
    ID: @Model!.Id
    Title: @Model.Title
    Price: @Model.Price
    ISBN: @Model.ISBN
    Remarks: @Model.Remarks
</pre>

Web.App.Frontend/Views/Book/SingleBook.cshtml
@{
    var book = HttpContextAccessor.HttpContext!.Session.Get<BookModel>("book");
}

<pre>
    ID: @book!.Id
    Title: @book.Title
    Price: @book.Price
    ISBN: @book.ISBN
    Remarks: @book.Remarks
</pre>

<pre>
    @(HttpContextAccessor.HttpContext!.Session.Get<bool>("isvalid"))
</pre>

Web.App.Frontend/Views/Gallery/About.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>About</title>
    <link href="~/styles/site-style.css" rel="stylesheet" asp-append-version="true" />
</head>

<body>

    <button type="button" onclick="showName()">Click to see name</button>
    <br />

    <h1 class="my-color my-bgcolor my-font">This is a h1 with class selector</h1>

    <h2 class="my-color my-bgcolor my-font">This is a h2 with class selector</h2>

    <p class="my-color my-bgcolor my-font">This is a p1 with class selector</p>

    <p class="my-font my-color my-bgcolor">This is a p2 with class selector</p>




    <h1 class="my-border">Heading 1</h1>
    <h2>Heading 2</h2>
    <h3>Heading 3</h3>

    <h5>Heading 5</h5>

    <p>This is a para 1</p>

    <p>This is a para 2</p>

    <p class="my-border">This is a para 3</p>



    <a href="~/images/admin-aijaz.png" target="_blank">
        <img loading="lazy" src="~/images/admin-aijaz.png" width="200" height="200" alt="Aijaz" asp-append-version="true" />
    </a>
    <br />

    <img loading="lazy" src="~/images/flower.jpg" alt="Flower" asp-append-version="true" width="200" height="200" />

    <br />

    <span id="my-color-style">This is a span 1</span>
    <br />

    <span>This is a span 2</span>
    <br />

    <span class="my-bgcolor">This is a span 3</span>
    <br />

    <small>This is a small 1</small>

    <script src="~/js/myScript.js" asp-append-version="true"></script>
</body>
</html>

Web.App.Frontend/Views/Gallery/Contact.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Contact</title>

    <link rel="stylesheet" href="~/styles/site-style.css" asp-append-version="true" />

    <link href="~/styles/my-style.css" rel="stylesheet" />

    <style>
        h1.new-class {
            background-color: darkred;
            color: bisque;
        }
    </style>

</head>


<body>
    <button type="button" onclick="showName()">Click to see name</button>
    <br />

    <h1 class="my-color my-bgcolor my-font">This is a h1 with class selector</h1>

    <h2 class="my-color my-bgcolor my-font">This is a h2 with class selector</h2>

    <p class="my-color my-bgcolor my-font">This is a p1 with class selector</p>

    <p class="my-font my-color my-bgcolor">This is a p2 with class selector</p>




    <h1 class="my-border">Heading 1</h1>
    <h2>Heading 2</h2>
    <h3>Heading 3</h3>

    <h5>Heading 5</h5>

    <p>This is a para 1</p>

    <p>This is a para 2</p>

    <p class="my-border">This is a para 3</p>



    <a href="~/images/admin-aijaz.png" target="_blank">
        <img loading="lazy" src="~/images/admin-aijaz.png" width="200" height="200" alt="Aijaz" asp-append-version="true" />
    </a>
    <br />

    <img loading="lazy" src="~/images/flower.jpg" alt="Flower" asp-append-version="true" width="200" height="200" />

    <br />

    <span id="my-color-style">This is a span 1</span>
    <br />

    <span>This is a span 2</span>
    <br />

    <span class="my-bgcolor">This is a span 3</span>
    <br />

    <small>This is a small 1</small>

    <h1 class="new-class" style="background-color:#F2184F;color: white;">THIS IS MY NEW H1</h1>
    <script src="~/js/myScript.js" asp-append-version="true"></script>
</body>
</html>

Web.App.Frontend/Views/Gallery/Create.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Create</title>
</head>

<body>
    <form asp-action="Create" asp-controller="Gallery" method="post">
        <pre>
        <input type="text" name="name" id="name" placeholder="Name.." /> <br />
        <input type="email" name="email" id="email" placeholder="Email.." /> <br />
        <input type="number" max="50" min="12" name="age" id="age" placeholder="Age" /> <br />

        <button type="submit" id="btn" name="btn" value="true">Submit</button> <br />
        <button id="clr" type="button">Clear Result</button>
        </pre>

        <pre>
        <h2>Result:</h2>

        </pre>
    </form>


    @if (ViewBag.isSubmitted == true)
    {
        <div id="print-form">
            <span>@ViewBag.Name</span>
            <span>@ViewBag.Email</span>
            <span>@ViewBag.Age</span>
        </div>
    }


    <script src="~/js/jquery-3.7.1.min.js"></script>
    <script>
        $(document).ready(function(){

            $('form').on('submit', function(event) {

                if($('#name').val().trim() != '' &&
                   $('#email').val().trim() != '' &&
                   $('#age').val() != '') {

                     var result = confirm("Are you sure to submit this form?");

                     if (!result) event.preventDefault();

                   }

                   else event.preventDefault();
            });

            $('#clr').click(function(){
                 $('#print-form').empty();
            });

            // $('#btn').click(function(){
            //    var username = $('#name').val();
            //    var email = $('#email').val();
            //    var age = $('#age').val();

            //    $('#print-form').text(`${username} - ${email} - ${age}`);

            // });
        });


        // document.getElementById('btn').addEventListener('click', function (event) {

        //     var result = confirm("Are you sure to submit this form?");

        //     if (!result) event.preventDefault();


        //     // var userName = document.getElementById('name').value;
        //     // var email = document.getElementById('email').value;
        //     // var age = document.getElementById('age').value;
        //     // document.getElementById('print-form').innerText = `${userName} - ${email} - ${age}`;

        // });
    </script>
</body>
</html>

Web.App.Frontend/Views/Gallery/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Picture Gallery</title>
    <link rel="stylesheet" href="~/styles/site-style.css" asp-append-version="true" />
</head>

<body>

    <button type="button" onclick="showName()">Click to see name</button> <br/>

    <h1 class="my-color my-bgcolor my-font">This is a h1 with class selector</h1>

    <h2 class="my-color my-bgcolor my-font">This is a h2 with class selector</h2>

    <p class="my-color my-bgcolor my-font">This is a p1 with class selector</p>

    <p class="my-font my-color my-bgcolor">This is a p2 with class selector</p>




    <h1 class="my-border">Heading 1</h1>
    <h2>Heading 2</h2>
    <h3>Heading 3</h3>

    <h5>Heading 5</h5>

    <p>This is a para 1</p>

    <p>This is a para 2</p>

    <p class="my-border">This is a para 3</p>



    <a href="~/images/admin-aijaz.png" target="_blank">
       <img loading="lazy" src="~/images/admin-aijaz.png" width="200" height="200" alt="Aijaz" asp-append-version="true" />
    </a> <br/>

    <img loading="lazy" src="~/images/flower.jpg" alt="Flower" asp-append-version="true" width="200" height="200" />
    
    <br/>

    <span id="my-color-style">This is a span 1</span> <br/>
     
    <span>This is a span 2</span>
    <br />

    <span class="my-bgcolor">This is a span 3</span> <br />

    <small>This is a small 1</small> 

    <h1 class="new-class">THIS IS MY NEW H1</h1>

    <p id="display"></p>

    <script src="~/js/myScript.js" asp-append-version="true"></script>

</body>
</html>

Web.App.Frontend/Views/Home/About.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>About Page</title>
</head>
<body>

    <h1>This is a Heading inside ABOUT page</h1>

    <h4>
        NAME: @HttpContextAccessor.HttpContext!.Session.GetString("Name") <br />
        AGE:  @HttpContextAccessor.HttpContext.Session.GetInt32("Age")
    </h4>


   @*  <h3>Person info</h3>

    <p style="font-weight:bold;color:cornflowerblue;">
        User: @TempData["Username"]<br />
        Age: @TempData["Age"]<br />
        Has job?: @((bool)TempData["HasJob"]! ? "YES" : "NO")<br />

        Complex anonymous type: @{
            var complexDataJson = TempData["ComplexData"]?.ToString();
            if (!string.IsNullOrEmpty(complexDataJson))
            {
                var complexData = JsonSerializer.Deserialize<dynamic>(complexDataJson);
                <text>@complexData</text>
            }
        }
    </p> *@


</body>
</html>

Web.App.Frontend/Views/Home/Book.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
</head>

<body>
    <h1>Book</h1>

    <table width="50%" border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Price</th>
                <th>ISBN</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Id</td>
                <td>@Model.Title</td>
                <td>@Model.Price</td>
                <td>@Model.ISBN</td>
            </tr>
        </tbody>
    </table>

</body>
</html>

Web.App.Frontend/Views/Home/BookList.cshtml
@model IEnumerable<BookModel>

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
</head>

<body>
    <h1>Book List</h1>

    <table width="50%" border="1">
        <thead>
            <tr>
                <th>S#</th>
                <th>ID</th>
                <th>Title</th>
                <th>Price</th>
                <th>ISBN</th>
            </tr>
        </thead>
        <tbody>
            @{
                var sno = 1;
            }
            @foreach (var book in Model)
            {
                <tr>
                    <td>@(sno++)</td>
                    <td>@book.Id</td>
                    <td>@book.Title</td>
                    <td>@book.Price</td>
                    <td>@book.ISBN</td>
                </tr>
            }
        </tbody>
    </table>

</body>
</html>

Web.App.Frontend/Views/Home/ContactUs.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Contact Page</title>
</head>
<body>

    <h1>This is a Heading inside CONTACT page</h1>

    <h4>
        NAME: @HttpContextAccessor.HttpContext!.Session.GetString("Name") <br />
        AGE:  @HttpContextAccessor.HttpContext.Session.GetInt32("Age")
    </h4>
</body>
</html>

Web.App.Frontend/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Home Page</title>
</head>

<body>
    <h1>This is a Heading inside INDEX page</h1>

    <h4>
        NAME: @HttpContextAccessor.HttpContext!.Session.GetString("Name") <br />
        AGE:  @HttpContextAccessor.HttpContext.Session.GetInt32("Age")
    </h4>

   @*  <p style="color:green; font-weight: bold;">
        @ViewBag.ComplexData.Name
    </p> *@

   @*  @{
        var name = "Aijaz";
        var age = 30;
        var isMarried = false;

        var username = "aijaz";
        var pass = 123;

        var weather = "may";
    } *@

    @* <p>
        My name is: @name <br/>
        My age is: @age <br/>
        I am @(isMarried? "Married" : "not Married")
        <hr/>
        @( _configuration.GetValue<string>("MyValue") )
    </p> *@


    @* @if (username == "aijaz" && pass == 123)
    {
        <h2>
            Wellcome! @username
        </h2>
    } 
    else {
        <h2>
            Invalid username: @username or Password!
        </h2>
    }


    @if(true){

    }

    @for (var i = 1; i <= 20; i++) {
        <p>Line: @(i) </p>
    }

    @{
    switch (weather)
    {
        case "january":
            <h4>It is: @weather</h4>
            break;

        case "feb":
            <h4>It is: @weather</h4>
            break;

        case "mar":
            <h4>It is: @weather</h4>
            break;

        case "apr":
            <h4>It is: @weather</h4>
            break;

        default:
            <h4 style="color: red;">No any weather was matched</h4>
            break;
    }
    } *@

   @*  <h3>Person info</h3>

    <p>
        User: @ViewBag.Username
        Age: @ViewBag.Age
        Has job?: @(ViewBag.HasJob == true? "YES" : "NO")

    </p> *@

</body>

</html>

Web.App.Frontend/Views/Home/PersonDetails.cshtml
@model Person

<!DOCTYPE html>
<html>
<head>
    <title>Person Details</title>
</head>

<body>
    <h1>Person Details</h1>

    <p>
        ID: @Model.Id
        NAME: @Model.Name
        AGE: @Model.Age
    </p>

</body>
</html>

Web.App.Frontend/Views/Home/SaveBook.cshtml
@model BookModel
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
</head>

<body>
    <a asp-controller="Product" asp-action="Products">BACK</a>

    <h1>Save Book</h1>

    <form asp-controller="Home" asp-action="SaveBook" method="post">
        <pre>
        <label asp-for="Id"></label>
        <input type="number" min="1" asp-for="Id" />

        <label asp-for="Title"></label>
        <input asp-for="Title" />

        <label asp-for="Price"></label>
        <input type="number" min="1" max="100" asp-for="Price" />

        <label asp-for="ISBN"></label>
        <input asp-for="ISBN" />

        <label asp-for="Remarks"></label>
        <textarea cols="20" rows="3" asp-for="Remarks"></textarea>

        <button type="submit">Save</button>
        </pre>
    </form>


    @if (Model != null)
    {
        <h2>@ViewBag.Title</h2>

        <p>Id: @Model.Id</p>
        <p>Title: @Model.Title</p>
        <p>Price: @Model.Price</p>
        <p>ISBN: @Model.ISBN</p>
        <p>Remarks: @Model.Remarks</p>
    }

</body>
</html>

Web.App.Frontend/Views/Product/Products.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Products List</title>

    <style>
        ul li{
            padding: 5px;
        }
    </style>


</head>
<body>
    <h1>Products List</h1>


    <ul>
        <li>
            <a asp-controller="Home" asp-action="Index">
                HOME
            </a>
        </li>

        <li>
            <a asp-controller="Home" asp-action="About">
                ABOUT
            </a>
        </li>

        <li>
            <a asp-controller="Home" asp-action="Contact">
                CONTACT
            </a>
        </li>

        <li>
            <a asp-controller="Home" asp-action="Book">
                BOOK
            </a>
        </li>

        <li>
            <a asp-controller="Home" asp-action="BookList">
                BOOK LIST
            </a>
        </li>

        <li>
            <a asp-controller="Home" asp-action="SaveBook">
                SAVE BOOK
            </a>
        </li>


        <li>
            <a asp-controller="Home" 
               asp-action="PersonDetails" 
               asp-route-id="1" 
               asp-route-name="Walidad Brohi"
               asp-route-age="30">
                View Person Details
            </a>
        </li>

    </ul>


</body>
</html>